### ISSUE TITLE
Error: No output location provided

### ISSUE THREAD

**Issue by lhb0803** [kovihq/sqltools-athena-driver#19]
`Error opening connection No output location provided. An output location is required either through the Workgroup result configuration setting or as an API input.`

I configured my query result location at my workgroup (primary)
But the error is raised....
Is it because I missed some configuration at VS-code setting?

![image](https://user-images.githubusercontent.com/58469407/169677097-7e8df714-a7af-4388-8d2a-23dd83180ae7.png)

**Comment by afeldman1** [comment]
Ran into same issue, made a PR for this: #20
